
#' Cohort Attrition -- Output Generation
#'
#' Using the tabular output generated by `ca_process`, this function will build a graph to
#' visualize the results. Each function configuration will output a bespoke ggplot. Theming can
#' be adjusted by the user after the graph has been output using `+ theme()`. Most graphs can
#' also be made interactive using `make_interactive_squba()`
#'
#' @param process_output *tabular input* || **required**
#'
#'   The tabular output produced by `ca_process`
#'
#' @param log_scale *boolean* || default to `FALSE`
#'
#'   A boolean indicating whether a log transformation should be applied to the
#'   y-axis of the output
#'
#' @param var_col *string* || defaults to `num_pts`
#'
#'   The name of the column that should be displayed on the plot for Exploratory analyses.
#'   The options are:
#'   - `num_pts`: raw patient count
#'   - `prop_retained_start`: proportion patients retained from the starting step, as indicated by `start_step_num`
#'   - `prop_retained_prior`: proportion patients retained from prior step
#'   - `prop_diff_prior`: proportion difference between each step and the prior step
#'
#' @param large_n *boolean* || defaults to `FALSE`
#'
#'   For Multi-Site analyses, a boolean indicating whether the large N
#'   visualization, intended for a high volume of sites, should be used. This
#'   visualization will produce high level summaries across all sites, with an
#'   option to add specific site comparators via the `large_n_sites` parameter.
#'
#' @param large_n_sites *vector* || defaults to `NULL`
#'
#'   When `large_n = TRUE`, a vector of site names that can add site-level information
#'   to the plot for comparison across the high level summary information.
#'
#' @return This function will produce a graph to visualize the results
#'         from `ca_process` based on the parameters provided. The default
#'         output is typically a static ggplot or gt object, but interactive
#'         elements can be activated by passing the plot through `make_interactive_squba`.
#'         For a more detailed description of output specific to each check type,
#'         see the PEDSpace metadata repository
#'
#' @example inst/example-ca_process_output.R
#'
#' @export
#'
ca_output <- function(process_output,
                      log_scale = FALSE,
                      var_col = 'num_pts',
                      large_n = FALSE,
                      large_n_sites = NULL){

  # extract output function
  output_function <- process_output %>% collect() %>% ungroup() %>% distinct(output_function) %>% pull()

  if(output_function == 'ca_ss_exp_cs'){
    ca_output <- ca_ss_exp_cs(process_output = process_output,
                              log_scale = log_scale,
                              output = var_col)
  }else if(output_function == 'ca_ms_exp_cs'){
    ca_output <- ca_ms_exp_cs(process_output = process_output,
                              log_scale = log_scale,
                              output = var_col,
                              large_n = large_n,
                              large_n_sites = large_n_sites)
  }else if(output_function == 'ca_ms_anom_cs'){
    ca_output <- ca_ms_anom_cs(process_output = process_output,
                               output = var_col,
                               large_n = large_n,
                               large_n_sites = large_n_sites)
  }else(cli::cli_abort('Please enter a valid output_function for this check'))

  return(ca_output)

}
